- name: Install ToDo app
  hosts: webservers
  remote_user: ec2-user

  tasks:
  - name: Install Git and Python
    ansible.builtin.yum:
      name:
        - git
        - python3
      state: present
    become: yes
