- name: Install ToDo app
  hosts: webservers
  remote_user: ec2-user

  tasks:
  - name: Install Git and Python
    ansible.builtin.yum:
      name:
        - git
        - python3
      state: present
    become: yes

  - name: Install Poetry
    ansible.builtin.shell:
      cmd: curl -SsL https://install.python-poetry.org | python3 -
      creates: /home/ex2-user/.local/bin/poetry

  - name: Create directory for ToDo app code
    ansible.builtin.file:
      path: /opt/todoapp
      mode: '777'
      state: directory
    become: yes

  - name: Clone latest version of code
    ansible.builtin.git:
      repo: 'https://github.com/anamicusoftwire/DevOps-Course-Starter.git'
      dest: /opt/todoapp
      version: exercise-4
